/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => HeaderAdjusterPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  increaseLevel: 1,
  decreaseLevel: 1
};
var HeaderAdjusterSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Header Adjuster Settings" });
    new import_obsidian.Setting(containerEl).setName("Default increase level").setDesc("The default number of levels to increase headers by.").addSlider((slider) => slider.setLimits(1, 5, 1).setValue(this.plugin.settings.increaseLevel).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.increaseLevel = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Default decrease level").setDesc("The default number of levels to decrease headers by.").addSlider((slider) => slider.setLimits(1, 5, 1).setValue(this.plugin.settings.decreaseLevel).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.decreaseLevel = value;
      await this.plugin.saveSettings();
    }));
  }
};

// src/commands.ts
var import_obsidian4 = require("obsidian");

// src/ui/LevelInputModal.ts
var import_obsidian2 = require("obsidian");
var LevelInputModal = class extends import_obsidian2.Modal {
  constructor(app, onSubmit, operation, settings) {
    super(app);
    this.onSubmit = onSubmit;
    this.operation = operation;
    this.settings = settings;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    const defaultLevel = this.operation === "increase" ? this.settings.increaseLevel : this.settings.decreaseLevel;
    contentEl.createEl("h3", { text: `Adjust Header Levels` });
    new import_obsidian2.Setting(contentEl).setName(`Levels to ${this.operation}`).setDesc(`Leave blank to use default (${defaultLevel})`).addText((text) => {
      text.inputEl.type = "number";
      text.setPlaceholder(String(defaultLevel));
      text.inputEl.min = "1";
      this.levelsInputEl = text.inputEl;
      this.levelsInputEl.focus();
    });
    new import_obsidian2.Setting(contentEl).setName("Start line (optional)").setDesc("Apply adjustment starting from this line number.").addText((text) => {
      text.inputEl.type = "number";
      text.setPlaceholder("e.g., 1");
      text.inputEl.min = "1";
      this.startLineInputEl = text.inputEl;
    });
    new import_obsidian2.Setting(contentEl).setName("End line (optional)").setDesc("Apply adjustment up to and including this line number.").addText((text) => {
      text.inputEl.type = "number";
      text.setPlaceholder("e.g., 50");
      text.inputEl.min = "1";
      this.endLineInputEl = text.inputEl;
    });
    new import_obsidian2.Setting(contentEl).addButton((button) => button.setButtonText("Submit").setCta().onClick(() => {
      const levels = this.levelsInputEl.value ? parseInt(this.levelsInputEl.value, 10) : void 0;
      const startLine = this.startLineInputEl.value ? parseInt(this.startLineInputEl.value, 10) : null;
      const endLine = this.endLineInputEl.value ? parseInt(this.endLineInputEl.value, 10) : null;
      if (this.levelsInputEl.value && (isNaN(levels != null ? levels : NaN) || (levels != null ? levels : 0) < 1)) {
        new import_obsidian2.Notice("Please enter a valid positive number for levels.");
        return;
      }
      if (startLine !== null && (isNaN(startLine) || startLine < 1)) {
        new import_obsidian2.Notice("Please enter a valid positive number for start line.");
        return;
      }
      if (endLine !== null && (isNaN(endLine) || endLine < 1)) {
        new import_obsidian2.Notice("Please enter a valid positive number for end line.");
        return;
      }
      if (startLine !== null && endLine !== null && endLine < startLine) {
        new import_obsidian2.Notice("End line cannot be before start line.");
        return;
      }
      this.onSubmit(levels, startLine, endLine);
      this.close();
    })).addButton((button) => button.setButtonText("Cancel").onClick(() => {
      this.close();
    }));
    const submitButton = this.contentEl.querySelector(".mod-cta");
    if (this.levelsInputEl && submitButton) {
      this.levelsInputEl.addEventListener("keydown", (event) => {
        if (event.key === "Enter") {
          event.preventDefault();
          submitButton.click();
        }
      });
    }
    if (this.startLineInputEl && submitButton) {
      this.startLineInputEl.addEventListener("keydown", (event) => {
        if (event.key === "Enter") {
          event.preventDefault();
          submitButton.click();
        }
      });
    }
    if (this.endLineInputEl && submitButton) {
      this.endLineInputEl.addEventListener("keydown", (event) => {
        if (event.key === "Enter") {
          event.preventDefault();
          submitButton.click();
        }
      });
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/headerUtils.ts
var import_obsidian3 = require("obsidian");
var HeaderObject = class {
  constructor(level, lineNumber, content, parent) {
    this.level = level;
    this.originalLevel = level;
    this.lineNumber = lineNumber;
    this.content = content;
    this.parent = parent;
    this.children = [];
  }
};
var HEADER_REGEX = /^(#{1,6})\s+(.*)$/;
function parseHeaders(editor, fromLine, toLine) {
  const headers = [];
  let lastHeader = null;
  const lineCount = editor.lineCount();
  const start = Math.max(0, fromLine);
  const end = Math.min(lineCount - 1, toLine);
  for (let i = start; i <= end; i++) {
    const lineText = editor.getLine(i);
    const match = lineText.match(HEADER_REGEX);
    if (match) {
      const currentLevel = match[1].length;
      const content = match[2];
      const newHeader = new HeaderObject(currentLevel, i + 1, content, null);
      if (lastHeader) {
        if (currentLevel > lastHeader.level) {
          newHeader.parent = lastHeader;
          lastHeader.children.push(newHeader);
        } else {
          let parentCandidate = lastHeader.parent;
          while (parentCandidate && parentCandidate.level >= currentLevel) {
            parentCandidate = parentCandidate.parent;
          }
          newHeader.parent = parentCandidate;
          if (parentCandidate) {
            parentCandidate.children.push(newHeader);
          }
        }
      }
      headers.push(newHeader);
      lastHeader = newHeader;
    }
  }
  return headers;
}
function updateHeaderLevels(headers, operation, levels) {
  const sortedHeaders = operation === "decrease" ? headers : [...headers].reverse();
  sortedHeaders.forEach((header) => {
    let newLevel;
    if (operation === "decrease") {
      newLevel = header.originalLevel - levels;
      newLevel = Math.max(1, newLevel);
      if (header.parent && newLevel <= header.parent.level) {
        newLevel = header.parent.level + 1;
      }
      header.level = Math.min(newLevel, 6);
    } else {
      newLevel = header.originalLevel + levels;
      newLevel = Math.min(6, newLevel);
      header.children.forEach((child) => {
        if (newLevel >= child.level) {
          newLevel = child.level - 1;
        }
      });
      header.level = Math.max(1, newLevel);
    }
  });
}
function applyHeaderChanges(editor, headers) {
  const sortedHeaders = [...headers].sort((a, b) => b.lineNumber - a.lineNumber);
  const potentialChanges = sortedHeaders.map((header) => {
    if (header.level === header.originalLevel) {
      return null;
    }
    const newHeaderPrefix = "#".repeat(header.level);
    const lineIndex = header.lineNumber - 1;
    return {
      from: { line: lineIndex, ch: 0 },
      to: { line: lineIndex, ch: header.originalLevel },
      // Replace old '#'s length
      text: newHeaderPrefix
    };
  });
  const actualChanges = potentialChanges.filter(
    (change) => change !== null
  );
  if (actualChanges.length > 0) {
    console.log("[Header Adjuster] Applying changes:", actualChanges);
    editor.transaction({
      changes: actualChanges
      // Pass the filtered array of valid EditorChange objects
    });
  } else {
    console.log("[Header Adjuster] No header level changes to apply.");
  }
}
function processHeaderAdjustment(editor, operation, levels, fromLine, toLine) {
  const startLine = fromLine != null ? fromLine : 0;
  const endLine = toLine != null ? toLine : editor.lineCount() - 1;
  if (startLine > endLine) {
    console.warn("[Header Adjuster] Start line is after end line, skipping adjustment.");
    return;
  }
  if (levels === 0) {
    console.log("[Header Adjuster] Adjustment level is 0, skipping.");
    return;
  }
  if (levels < 0) {
    console.warn("[Header Adjuster] Adjustment level is negative, skipping.");
    return;
  }
  console.log(`[Header Adjuster] Parsing headers from line ${startLine + 1} to ${endLine + 1}`);
  const headersInRange = parseHeaders(editor, startLine, endLine);
  if (headersInRange.length === 0) {
    new import_obsidian3.Notice("No headers found in the specified range/selection.");
    return;
  }
  console.log(`[Header Adjuster] Found ${headersInRange.length} headers in range.`);
  updateHeaderLevels(headersInRange, operation, levels);
  applyHeaderChanges(editor, headersInRange);
  const changedCount = headersInRange.filter((h) => h.level !== h.originalLevel).length;
  if (changedCount > 0) {
    new import_obsidian3.Notice(`Adjusted ${changedCount} header(s).`);
  } else {
    new import_obsidian3.Notice(`No header levels needed adjustment in the range.`);
  }
}

// src/commands.ts
function openLevelInputModal(plugin, operation) {
  const modal = new LevelInputModal(
    plugin.app,
    // --- Callback when modal submits ---
    (levelsInput, startLineInput, endLineInput) => {
      var _a;
      const levels = levelsInput != null ? levelsInput : operation === "increase" ? plugin.settings.increaseLevel : plugin.settings.decreaseLevel;
      const startLine = startLineInput ? startLineInput - 1 : 0;
      const endLine = endLineInput ? endLineInput - 1 : void 0;
      const editor = (_a = plugin.app.workspace.activeEditor) == null ? void 0 : _a.editor;
      if (!editor) {
        new import_obsidian4.Notice("No active editor found.");
        return;
      }
      processHeaderAdjustment(editor, operation, levels, startLine, endLine);
    },
    // --- Pass operation and settings to modal ---
    operation,
    plugin.settings
  );
  modal.open();
}
function handleDefaultAdjustment(plugin, operation) {
  var _a;
  const editor = (_a = plugin.app.workspace.activeEditor) == null ? void 0 : _a.editor;
  if (!editor) {
    new import_obsidian4.Notice("No active editor found.");
    return;
  }
  const levels = operation === "increase" ? plugin.settings.increaseLevel : plugin.settings.decreaseLevel;
  processHeaderAdjustment(editor, operation, levels);
}
function handleSelectionAdjustment(plugin, editor, operation) {
  const levels = operation === "increase" ? plugin.settings.increaseLevel : plugin.settings.decreaseLevel;
  const selection = editor.listSelections()[0];
  if (!selection) return;
  const from = selection.anchor.line < selection.head.line ? selection.anchor : selection.head;
  const to = selection.anchor.line >= selection.head.line ? selection.anchor : selection.head;
  const fromLine = from.line;
  const toLine = to.line;
  processHeaderAdjustment(editor, operation, levels, fromLine, toLine);
}

// src/main.ts
var HeaderAdjusterPlugin = class extends import_obsidian5.Plugin {
  async onload() {
    console.log("Loading Header Adjuster Plugin");
    await this.loadSettings();
    this.addRibbonIcon("heading", "Adjust headers", (event) => {
      const menu = new import_obsidian5.Menu();
      menu.addItem(
        (item) => item.setTitle("Increase level...").setIcon("plus-square").onClick(() => openLevelInputModal(this, "increase"))
      );
      menu.addItem(
        (item) => item.setTitle("Decrease level...").setIcon("minus-square").onClick(() => openLevelInputModal(this, "decrease"))
      );
      menu.addSeparator();
      menu.addItem(
        (item) => item.setTitle("Increase level by 1 (Document)").setIcon("chevron-up").onClick(() => {
          var _a;
          const editor = (_a = this.app.workspace.activeEditor) == null ? void 0 : _a.editor;
          if (!editor) {
            new import_obsidian5.Notice("No active editor found.");
            return;
          }
          processHeaderAdjustment(editor, "increase", 1);
        })
      );
      menu.addItem(
        (item) => item.setTitle("Decrease level by 1 (Document)").setIcon("chevron-down").onClick(() => {
          var _a;
          const editor = (_a = this.app.workspace.activeEditor) == null ? void 0 : _a.editor;
          if (!editor) {
            new import_obsidian5.Notice("No active editor found.");
            return;
          }
          processHeaderAdjustment(editor, "decrease", 1);
        })
      );
      menu.addSeparator();
      menu.addItem(
        (item) => item.setTitle(`Increase level by (+${this.settings.increaseLevel}) (Selection)`).setIcon("plus-square").onClick(() => {
          var _a;
          const editor = (_a = this.app.workspace.activeEditor) == null ? void 0 : _a.editor;
          if (editor && editor.somethingSelected()) {
            handleSelectionAdjustment(this, editor, "increase");
          } else {
            new import_obsidian5.Notice("Select text containing headers first.");
          }
        })
      );
      menu.addItem(
        (item) => item.setTitle(`Decrease level by  (-${this.settings.decreaseLevel}) (Selection)`).setIcon("minus-square").onClick(() => {
          var _a;
          const editor = (_a = this.app.workspace.activeEditor) == null ? void 0 : _a.editor;
          if (editor && editor.somethingSelected()) {
            handleSelectionAdjustment(this, editor, "decrease");
          } else {
            new import_obsidian5.Notice("Select text containing headers first.");
          }
        })
      );
      menu.showAtMouseEvent(event);
    });
    this.addCommand({
      id: "increase-header-level",
      name: "Increase header level...",
      callback: () => openLevelInputModal(this, "increase")
    });
    this.addCommand({
      id: "decrease-header-level",
      name: "Decrease header level...",
      callback: () => openLevelInputModal(this, "decrease")
    });
    this.addCommand({
      id: "increase-header-level-default",
      name: `Increase header level by ${this.settings.increaseLevel} (entire document)`,
      callback: () => handleDefaultAdjustment(this, "increase")
    });
    this.addCommand({
      id: "decrease-header-level-default",
      name: `Decrease header level by ${this.settings.decreaseLevel} (entire document)`,
      callback: () => handleDefaultAdjustment(this, "decrease")
    });
    this.addCommand({
      id: "increase-header-level-selection-default",
      name: `Increase header level in selection by ${this.settings.increaseLevel}`,
      editorCheckCallback: (checking, editor, view) => {
        if (editor.somethingSelected()) {
          if (!checking) {
            handleSelectionAdjustment(this, editor, "increase");
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "decrease-header-level-selection-default",
      name: `Decrease header level in selection by ${this.settings.decreaseLevel}`,
      editorCheckCallback: (checking, editor, view) => {
        if (editor.somethingSelected()) {
          if (!checking) {
            handleSelectionAdjustment(this, editor, "decrease");
          }
          return true;
        }
        return false;
      }
    });
    this.addSettingTab(new HeaderAdjusterSettingTab(this.app, this));
  }
  onunload() {
    console.log("Unloading Header Adjuster Plugin");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};

/* nosourcemap */