#:schema https://creativeprojects.github.io/resticprofile/jsonschema/config-1.json
#
# indentation is not needed but it makes it easier to read ;)
#
version = "1"

[global]
  default-command = "snapshots"
  restic-stale-lock-age = "2h"

[nixos]
  base-dir = "~"
  repository = "/mnt/backup/nixos-backup"
  initialize = false
  force-inactive-lock = true

  [nixos.env]
    RESTIC_PASSWORD = "0539Carissa"

  [nixos.backup]
    verbose = true
    dry-run = false
    schedule-log = "~/Documents/restic/restic.log"
    exclude-caches = true
    tag = ["personal"]
    source = ["Documents", "Desktop", "Downloads"]
    exclude = ["Documents/restic"]
    schedule-lock-wait = "2h"
    run-after = "~/scripts/backup-success.sh"
    run-after-fail = 'printf "WARNING! FAILED Resticprofile NixOS backup @ /media/backup/nixos-backup on {{ .Now.Format "02 Jan 06 15:04 GMT+8" }}. \nError Message: ${ERROR_MESSAGE} \nError: ${ERROR_STDERR}"  | mail -s "WARNING! FAILED NixOS backup on {{ .Now.Format "02 Jan 06 15:04" }}" mattechane@gmail.com'

  [nixos.retention]
    before-backup = false
    after-backup = true
    keep-daily = 7
    keep-weekly = 4
    keep-monthly = 6
    keep-yearly = 10
    keep-within = "3h"
    prune = true
